version: '3.8'

services:
  eld_app:
    build: .
    container_name: django-backend
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn eld_backend.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: eld_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
